# Generated by Django 5.1.2 on 2024-11-26 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_tool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifyprofile',
            old_name='profile_image',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='spotifyprofile',
            name='following',
        ),
        migrations.RemoveField(
            model_name='spotifyprofile',
            name='user',
        ),
    ]
