# Generated by Django 5.1.2 on 2024-11-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_tool', '0002_rename_profile_image_spotifyprofile_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('playlist', 'track_id')},
        ),
    ]
