# Generated by Django 5.1.2 on 2024-11-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_tool', '0003_alter_track_track_id_alter_track_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='analyzed',
            field=models.BooleanField(default=False),
        ),
    ]
