# Generated by Django 5.1.2 on 2024-11-27 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_tool', '0004_playlist_analyzed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['name']},
        ),
    ]
