# Generated by Django 5.1.2 on 2024-11-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_tool', '0006_playlist_spotify_url_track_spotify_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='artist_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
