# Generated by Django 5.1.2 on 2024-11-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_tool', '0008_artist_remove_track_artist_remove_track_artist_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='track',
            name='popularity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
